//[nam][BaseObject]
//[des][Represent base object in game]
//[ret][None]
//[arg][None]
//[cla][None]

//[nam][Allah]
//[des][Ackbar]
//[ret][1]
//[arg][2]
//[cla][3]

//[nam][sadsad]
//[des][asdsda]
//[ret][asdsda]
//[arg][2adssad]
//[cla][3dasda]